program: trainer.py
method: bayes
metric:
  goal: maximize
  name: Relative Time (Process)
parameters:
  trainer:
    parameters:
      max_grad_norm:
        max: 1
        min: 0.1
        distribution: uniform
      entropy_coef:
        max: 0.03
        min: 0.0
        distribution: uniform
      rollout_len:
        max: 2048
        min: 128
        distribution: int_uniform
      # seq_model:
      #     n_layers:
      #       max: 8
      #       min: 2
      #       distribution: int_uniform
      #     n_heads:
      #       max: 8
      #       min: 2
      #       distribution: int_uniform
      #     d_model:
      #       max: 256
      #       min: 64
      #       distribution: int_uniform
      #     d_head:
      #       max: 128
      #       min: 32
      #       distribution: int_uniform
      #     d_ffc:
      #       max: 256
      #       min: 64
      #       distribution: int_uniform
      #     eta:
      #       max: 8
      #       min: 2
      #       distribution: int_uniform
      #     r:
      #       max: 4
      #       min: 1
      #       distribution: int_uniform
      optimizer:
        parameters:
          learning_rate:
            max: 0.0025
            min: 0.000025
            distribution: uniform
      # d_critic:
      #   max: 256
      #   min: 64
      #   distribution: int_uniform
      # d_actor:
      #   max: 256
      #   min: 64
      #   distribution: int_uniform
