# @package _global_
tags: ["HalfCheetah-v4"]
project_name: "ReLiT"
seed: 1
steps: 5000000
log_interval: 10000
# eval_interval: 500000
# eval_episodes: 100
# eval_only: false
# videos: false
# record_fps: 30
# save_interval: 500000
# save_dir: "./checkpoints"
# save_tag: "arelit_half-cheetah-v4"
continuous_actions: true
task: 
  task: "mujoco"
  env_name: "HalfCheetah-v4"
  max_episode_steps: 1000
  seed: null

trainer:
  agent: ppo
  seq_model:
    name: arelit
    n_layers: 4
    d_model: 128
    d_head: 64
    d_ffc: 128
    n_heads: 4
    eta: 4
    r: 2
    reset_hidden_on_terminate: true
  env_pool: async
  d_actor: 256
  d_critic: 256
  num_envs: 8
  rollout_len: 1024
  sequence_length: null
  anneal_lr: true
  gamma: 0.99
  gae_lambda: 0.95
  num_minibatches: 4
  update_epochs: 10
  norm_adv: true
  clip_coef: 0.2
  ent_coef: 
    initial:  0.0003
    final:  null
    max_decay_steps: 10000
    power: 1
  vf_coef: 0.5
  max_grad_norm: 0.1
  optimizer: 
    learning_rate: 
      initial: 0.00025
      final: null
      max_decay_steps: 10000
      power: 1.0

use_wandb: true
